# Generated by Django 3.0.2 on 2020-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDirectory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.IntegerField(default=2333),
            preserve_default=False,
        ),
    ]
