export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const FETCH_START='FETCH_START';
export const FETCH_SUCCESS='FETCH_SUCCESS';
export const FETCH_FAIL='FETCH_FAIL';

export const ADDCART_START='ADDCART_START';
export const ADDCART_SUCCESS='ADDCART_SUCCESS';
export const ADDCART_FAIL='ADDCART_FAIL';
export const CLEARCART='CLEARCART';
export const REMOVECARTITEM='REMOVECARTITEM';

export const CHECKOUT_START='CHECKOUT_START';
export const CHECKOUT_SUCCESS='CHECKOUT_SUCCESS';
export const CHECKOUT_FAIL='CHECKOUT_FAIL';
export const SEARCHITEMS='SEARCHITEMS';

