# Generated by Django 3.0.2 on 2020-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
