# Generated by Django 3.0.2 on 2020-10-06 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsDir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='status',
            new_name='sold_status',
        ),
        migrations.AddField(
            model_name='items',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='posted_by',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
