# Generated by Django 3.0.2 on 2020-10-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsDir', '0003_items_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='version',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='sold_to',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
