# Generated by Django 3.0.2 on 2020-10-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsDir', '0004_auto_20201014_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
